---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: update aptitude
      apt: update_cache=yes
    - name: upgrade packages
      apt: upgrade=full
    - name: set locale
      command: sudo locale-gen UTF-8
    - name: install the latest version of emacs
      apt: pkg=emacs24 state=installed
    - name: install git
      apt: pkg=git state=installed
    - name: install ocaml packages
      action: apt pkg={{item}} state=installed
      with_items:
      - curl
      - build-essential
      - m4
      - zlib1g-dev
      - libssl-dev
      - ocaml
      - ocaml-native-compilers
      - opam
    - name: install OPAM
      command: opam init -y $$ eval `opam config env`
    - name: quick fix for OPAM:
      command: echo ". /home/vagrant/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true" >> ~/.bashrc
    - name: fix for OPAM + ocamlfind
      command: echo "let () = try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH") with Not_found -> ();;" >> ~/.ocamlinit
    - name: install repl and editor plugins
      command: opam install utop merlin
